name: shadowshare
 
on:
  push:
  workflow_dispatch: #手动调试按钮
  schedule:
    - cron: '*/180 * * * *'
jobs:
  buzhou1:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Timezone #UTC+0 → UTC+8
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: pip
        run: | #安装pip包
          pip install -r ./utils/pool/requirements.txt
          pip install -r ./utils/clashcheck/requirements.txt
      - name: download
        run: curl -o ./jiedian0.txt https://config.v2cross.com/profilesv2/encryptcfg
      - name: jiemi1
        run: python3 decode.py
      - name: init
        run: | 
           git config pull.rebase false
           git config --local user.name "GitHub Actions"
           git config --local user.email "actions@github.com"
      - name: push
        run: | 
           git pull origin main && git add . && git commit -m "$(date '+%Y.%m.%d %H:%M:%S') 节点入库" && git push origin main
     
