name: shadowshare
 
on:
  push:
  schedule:
    - cron: '*/60 * * * *'
jobs:
  buzhou1:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Checkout codes' # 步骤一，获取仓库代码
        uses: actions/checkout@v1
