name: shadowshare
 
on:
  workflow_dispatch: #手动调试按钮
  schedule:
    - cron: '*/180 * * * *'
jobs:
  buzhou1:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Checkout codes' # 步骤一，获取仓库代码
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4 #python环境
        with:
          python-version: '3.x'       #python 3.x
          cache: 'pip'                #pip cache
      - name: pip
        run: | #安装pip包
          pip install -r ./utils/pool/requirements.txt
          pip install -r ./utils/clashcheck/requirements.txt
      - name: download
        run: curl -o ./jiedian0.txt https://config.v2cross.com/profilesv2/encryptcfg
      - name: jiemi1
        run: python3 decode.py
      - name: init
        run: | 
           git config pull.rebase false
           git config --local user.name "GitHub Actions"
           git config --local user.email "actions@github.com"
      - name: push
        run: | 
           git pull origin main && git add . && git commit -m "$(date '+%Y.%m.%d %H:%M:%S') 节点入库" && git push origin main
     
