name: shadowshare
 
on:
  workflow_dispatch: #手动调试按钮
  schedule:
    - cron: '*/180 * * * *'
jobs:
  job1:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Initialization environment
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pycryptodomex
      - name: download
        run: curl -o ./jiedian0.txt https://config.v2cross.com/profilesv2/encryptcfg
      - name: jiemi1
        run: python3 decode.py
      - name: base64encode
        run: openssl base64 -in ./jiedian.txt -out ./jiedian.txt
      - name: init
        run: | 
           git config pull.rebase false
           git config --local user.name "GitHub Actions"
           git config --local user.email "actions@github.com"
      - name: push
        run: | 
           git pull origin main && git add . && git commit -m "$(date '+%Y.%m.%d %H:%M:%S') 节点入库" && git push origin main
     
