name: shadowshare
 
on:
  workflow_dispatch: #手动调试按钮
  schedule:
    - cron: '*/180 * * * *'
jobs:
  buzhou1:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Checkout codes' # 步骤一，获取仓库代码
        uses: actions/checkout@v3
      - name: download
        run: curl -o ./jiedian.txt https://config.v2cross.com/profilesv2/encryptcfg
      - name: jiemi
        run: openssl enc -d -aes-128-cbc -in ./jiedian.txt -out ./jiedian.txt -pass pass:8YfiQ8wrkziZ5YFa -a
      - name: init
        run: | 
           git config pull.rebase false
           git config --local user.name "GitHub Actions"
           git config --local user.email "actions@github.com"
      - name: push
        run: | 
           git pull origin main && git add . && git commit -m "$(date '+%Y.%m.%d %H:%M:%S') 节点入库" && git push origin main
     
